# project:
#   type: website

# website:
#   title: "blog_migration"
#   navbar:
#     right:
#       - about.qmd
#       - icon: github
#         href: https://github.com/
#       - icon: twitter
#         href: https://twitter.com
# format:
#   html:
#     theme: cosmo
#     css: styles.css
project:
  type: website
  output-dir: docs


